services:
  - type: worker
    name: cinema-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python cinema-bot.py
    envVars:
      - key: BOT_TOKEN
        value: 7602655211:AAEbUa1-rPtIe-JZ02sBW9wT0PZ_WzJF2Wk
